In [1]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', 30)

In [2]:
evometrics_df = pd.read_csv("results/evometrics.csv")

/tmp/ipykernel_4772/1288837588.py:1: DtypeWarning: Columns (0: commitprevious) have mixed types. Specify dtype option on import or set low_memory=False.
  evometrics_df = pd.read_csv("results/evometrics.csv")

In [3]:
evometrics_df[['file', 'method']].head()

,file,method
0,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/StopBits,getStrings()
1,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/StopBits,fromStringIndex(int)
2,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/StopBits,getStringIndex(StopBits)
3,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/StopBits,getDefault()
4,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/SerialPort,getOutputStream()

In [4]:
evometrics_df[evometrics_df['method'] == 'getSkipBuild()'].to_csv("results/evometrics_getSkipBuild.csv", index=False)

In [5]:
evometrics_df[evometrics_df['method'] == 'getSkipBuild()']

,project,commit,commitprevious,release,file,method,BOM,TACH,FCH,LCH,CHO,FRCH,CHD,WCH,WCD,WFR,ATAF,LCA,LCD,CSB,CSBS,ACDF
16690,cdt,96ef6bcb785619cb23e2aad86dd44a207177b5bb,NaN,1,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,0,0,0,0,0,0.000000,0.000,0.000000,0,0.0,0,0.000000,0,0.000000,0.000000
102825,cdt,ab4138f805ebc028b6ed5008d506cab4e2232272,96ef6bcb785619cb23e2aad86dd44a207177b5bb,2,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,10,2,2,1,1,0.263158,10.000,0.263158,1,10.0,10,0.263158,10,0.333333,0.263158
184773,cdt,0bd96c77efa3d6b5ebbad2d161ca02fe467f8969,ab4138f805ebc028b6ed5008d506cab4e2232272,3,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,0,2,2,0,1,0.000000,5.000,0.131579,1,0.0,10,0.263158,10,0.333333,0.263158
266721,cdt,0c257b0bbdb183f02cf0845a916cea2e628bfd95,0bd96c77efa3d6b5ebbad2d161ca02fe467f8969,4,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,4,2,4,1,2,0.117647,6.500,0.183437,4,2.0,4,0.117647,14,0.466667,0.190402
348669,cdt,e3e551cfc8c3e990487c299b01184d0cf762d092,0c257b0bbdb183f02cf0845a916cea2e628bfd95,5,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,0,2,4,0,2,0.000000,3.250,0.091718,4,0.0,4,0.117647,14,0.466667,0.190402
430617,cdt,7f494ba11204b87606f5e164fe3785ba5a63cda7,e3e551cfc8c3e990487c299b01184d0cf762d092,6,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,0,2,4,0,2,0.000000,1.625,0.045859,4,0.0,4,0.117647,14,0.466667,0.190402

In [6]:
evometrics_df[evometrics_df['method'] == 'setupSkipBuild()'].to_csv("results/evometrics_setupSkipBuild.csv", index=False)