In [39]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', 30)

In [40]:
evometrics_df = pd.read_csv("results/evometrics.csv")

/tmp/ipykernel_297888/1288837588.py:1: DtypeWarning: Columns (0: commitprevious) have mixed types. Specify dtype option on import or set low_memory=False.
  evometrics_df = pd.read_csv("results/evometrics.csv")

In [41]:
evometrics_df[['file', 'method']].head()

,file,method
0,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/StopBits,getStrings()
1,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/StopBits,fromStringIndex(int)
2,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/StopBits,getStringIndex(StopBits)
3,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/StopBits,getDefault()
4,repo1/native/org.eclipse.cdt.native.serial/src/org/eclipse/cdt/serial/SerialPort,getOutputStream()

In [42]:
evometrics_df[evometrics_df['method'] == 'getSkipBuild()']

,project,commit,commitprevious,release,file,method,BOM,TACH,FCH,LCH,CHO,FRCH,CHD,WCH,WCD,WFR,ATAF,LCA,LCD,CSB,CSBS,ACDF
16690,cdt,96ef6bcb785619cb23e2aad86dd44a207177b5bb,NaN,1,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,0,0,0,0,0,0.000000,0.000,0.000000,0,0.0,0,0.000000,0,0.000000,0.000000
150002,cdt,ab4138f805ebc028b6ed5008d506cab4e2232272,96ef6bcb785619cb23e2aad86dd44a207177b5bb,2,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,10,2,2,1,1,0.263158,10.000,0.263158,1,10.0,10,0.263158,10,0.333333,0.263158
231950,cdt,0bd96c77efa3d6b5ebbad2d161ca02fe467f8969,ab4138f805ebc028b6ed5008d506cab4e2232272,3,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,0,2,2,0,1,0.000000,5.000,0.131579,1,0.0,10,0.263158,10,0.333333,0.263158
313898,cdt,0c257b0bbdb183f02cf0845a916cea2e628bfd95,0bd96c77efa3d6b5ebbad2d161ca02fe467f8969,4,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,4,2,4,1,2,0.117647,2.500,0.065789,4,2.0,4,0.117647,14,0.466667,0.190402
395846,cdt,e3e551cfc8c3e990487c299b01184d0cf762d092,0c257b0bbdb183f02cf0845a916cea2e628bfd95,5,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,0,2,4,0,2,0.000000,5.250,0.150542,4,0.0,4,0.117647,14,0.466667,0.190402
477794,cdt,7f494ba11204b87606f5e164fe3785ba5a63cda7,e3e551cfc8c3e990487c299b01184d0cf762d092,6,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,getSkipBuild(),1,0,2,4,0,2,0.000000,2.625,0.075271,4,0.0,4,0.117647,14,0.466667,0.190402

In [43]:
evometrics_df[evometrics_df['method'] == 'setupSkipBuild()']

,project,commit,commitprevious,release,file,method,BOM,TACH,FCH,LCH,CHO,FRCH,CHD,WCH,WCD,WFR,ATAF,LCA,LCD,CSB,CSBS,ACDF
491690,cdt,2d87281d09f9dbc872d4652e578ceaebf483a27e,7f494ba11204b87606f5e164fe3785ba5a63cda7,7,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,setupSkipBuild(),7,0,0,0,0,0,0.000000,0.0,0.000000,0,0.0,0,0.000000,0,0.000000,0.000000
608293,cdt,9e17fbca4ff08df9a0895f0991d2e8d165468376,2d87281d09f9dbc872d4652e578ceaebf483a27e,8,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,setupSkipBuild(),7,0,0,0,0,0,0.000000,0.0,0.000000,0,0.0,0,0.000000,0,0.000000,0.000000
690245,cdt,909e2294b144c32f5783ae5071a8b54c7a03ba44,9e17fbca4ff08df9a0895f0991d2e8d165468376,9,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,setupSkipBuild(),7,0,0,0,0,0,0.000000,0.0,0.000000,0,0.0,0,0.000000,0,0.000000,0.000000
772200,cdt,3447d2a00a7767620d12a9b8ae478e88f446caac,909e2294b144c32f5783ae5071a8b54c7a03ba44,10,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,setupSkipBuild(),7,0,0,0,0,0,0.000000,0.0,0.000000,0,0.0,0,0.000000,0,0.000000,0.000000
854155,cdt,452d57aa7aa1bd4dee015f245a0e681aaaf600d5,3447d2a00a7767620d12a9b8ae478e88f446caac,11,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,setupSkipBuild(),7,12,11,11,1,1,1.333333,0.0,0.000000,10,12.0,12,1.333333,12,0.571429,1.333333
936110,cdt,01ae52986483dbc6d42c59e0e10730a8aadd4467,452d57aa7aa1bd4dee015f245a0e681aaaf600d5,12,repo1/toolchains/arduino/org.eclipse.cdt.arduino.core.tests/src/org/eclipse/cdt/arduino/core/tests/FullIntegration,setupSkipBuild(),7,2,11,12,1,2,0.181818,12.0,1.333333,21,1.0,2,0.181818,14,0.666667,0.757576